### ISSUE TITLE
No folder called basicSSDLProject

### ISSUE THREAD

**Issue by adamhartleb** [Apress/cpp-for-lazy-programmers#1]
Chapter 1 in the book says to:

> Make a copy of a working project folder. The source code has one named basicSSDLProject. It knows where to find SDL and SSDL in the source code, so keep your copy in the same location.

But there's no such folder to be found. I tried just opening the .sln file for "ch1" in Visual Studio 2017 and running Build > Build Solution, but it just results in the following:

![image](https://user-images.githubusercontent.com/13157406/66260327-22582200-e772-11e9-8305-a9002f2f256b.png)

I do see the header files listed in "External Dependencies", but I'm not sure how the paths find them as they are:

> ..\..\external\SDL2\include;..\..\external\SSDL\include

I'm not sure what that path is relative to. I think it's to the solution file, but there is no "external" folder up two directories from the .sln file.

**Comment by adamhartleb** [comment]
It's alright, I got it working just by copying all the .dll files into the project directory.

**Comment by briggs-w** [comment]
Good. The path is relative to the .vcxproj files. Two folders up you'll find the external/ folder.
