### ISSUE TITLE
Compiling Resources for Unix

### ISSUE THREAD

**Issue by mikecarey134** [Apress/cpp-for-lazy-programmers#2]
For compiling SSDL on Unix you need to download following libs before SSDL will compile using the provided makefile 

SDL2 https://www.libsdl.org/download-2.0.php
SDL_Mixer https://www.libsdl.org/projects/SDL_mixer/
SDL_Image https://www.libsdl.org/projects/SDL_mixer/
SDL_ttf https://www.libsdl.org/projects/SDL_ttf/

I ran ./configure from each source then make 
I was then able to make install each to get the SSDL makefile to build without any errors

**Comment by jglathe** [comment]
SDL_Image is here: https://www.libsdl.org/projects/SDL_image/

**Comment by briggs-w** [comment]
Instructions above are correct.
