### ISSUE TITLE
the program window is flickering when `ssin` is in the program.

### ISSUE THREAD

**Issue by gustavklopp** [Apress/cpp-for-lazy-programmers#5]
`sout` doesn't cause any problem.
But for any program with `ssin` inside, it causes the window of the program to flicker.
It's a flickering with no regularity, very fast.
But I can enter a value, it's recorded and then `sout` displays the result. The flickering stops when the result appears.

I'm on Linux (I've installed the Microsoft fonts and all the fonts are displayed correctly if only `sout` is called).
Thanks!

**Comment by briggs-w** [comment]
Sorry I just found this. In the new repository, I have my email address so people can contact me more quickly.

You might try the new repository at https://github.com/Apress/cpp20-for-lazy-programmers. If the problem persists, please update your distribution and g++, be sure there's still a problem, and provide a lot of info (a sample program that has this problem, detail on your installation including distribution and version, and version of g++).

**Comment by gustavklopp** [comment]
Well I am on another things now... Thanks for the reply though! It was a very nice book!
